# Generated by Django 3.1.7 on 2021-04-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set(),
        ),
    ]
